name: bayesian-modelling-tutorial
channels:
- conda-forge
- defaults
- ericmjl
dependencies:
- python=3.7
- jupyter
- pymc3
- pip
- seaborn
- matplotlib
- numpy>=1.16
- scipy
- pandas
- jupyterlab
- tqdm
- missingno
- scikit-learn
- cython
- nodejs
- pyjanitor
- xarray
- pandoc
- black
- nbstripout
- pylint
- arviz
- theano>=1.0.4
- ipykernel
- hvplot
- bokeh
- holoviews
